### ISSUE TITLE
Comparing Neataptic Vs Neat

### ISSUE THREAD

**Issue by cyberwlf** [wagenaartje/neataptic#103]
Hi @wagenaartje, 

I'm wondering, do you have any tests comparing your algorithm with NEAT? I was thinking about implementing my own version of NEAT, but recently I found your lib. It seems to work pretty well, but I don't know what to expect from evolution algorithms in general (I came from supervised learning side). 

It would be awesome to see some charts if there are any. Thanks.

**Comment by wagenaartje** [comment]
Glad to see someone else getting interested in evolution algorithms. Unfortunately I don't have any comparison tests. I think that Neataptic will be able to fit smaller networks to problems than NEAT can due to a lot more parameter options and parameters. On the other hand, this will increase the amount of iterations till convergence.

Would be interesting to see some comparison tests on this, unfortunately I don't have time atm to set them up myself.

**Comment by cyberwlf** [comment]
I think neuroevolution is hot right now. It feels like a more natural way to make self-learning machines.
Thank you for the contribution to this field!

Probably I'll make an attempt to create a convolutional network with your lib (this is required for my task). What do you think about this approach:  

Let's make several Neataptic instances, each for the corresponding kernel:

```
Neat1(kernel1)
Neat2(kernel2)
Neat3(kernel3)
...
NeatN(kernelN)
```

Activating in such way:

`Input -> [Neat1(), Neat2(), Neat3(), ... NeatN()].activate() -> NeatMain().activate() -> Output`

And let's link genomes together:

`HugeGenome = [GMain(), GN1(), GN2(), GN3(), ... GNN()] `

I think now we can evaluate each HugeGenome as usual and propagate scores down to its parts to select the best of them. Of course, populations of kernels can be smaller (let's say 10% of the main net size). But instead, we can form different sets with the same main genome:
```

HugeGenome1 = [GMain(), GN1_v1(), GN2_v1(), GN3_v1(), ... GNN_v1()] 
HugeGenome2 = [GMain(), GN1_v2(), GN2_v2(), GN3_v2(), ... GNN_v2()] 
HugeGenome3 = [GMain(), GN1_v3(), GN2_v3(), GN3_v3(), ... GNN_v3()] 
...
// v1, v2, v3 - top 3 genomes from each kernal group
```

I think you already have a better idea how to implement this. Will be glad to hear a couple words!

**Comment by wagenaartje** [comment]
I have been looking at ways to create convolutional networks some time in the past. The only reason I did not implement it because I was unable to figure out a way to make it work for backpropagation _and_ evolution.

I think what you are doing is creating 'groups' of networks and activating them together to assign 'groups' of networks a score, but I don't see where the shared weights come into play.

**However**, it would actually be really easy to implement convolutional networks if you are just interested in training through evolution. You just need to make it possible for networks to have shared weights, by giving them an ID or something like that. This could be done by creating objects out of weights for instance. Or, you could look into making `Connection` objects having multiple input-output pairs.

But i'm no expert on convolutional networks at all, so maybe I misread something in your reply!

**Comment by cyberwlf** [comment]
Yeah, I'm thinking exactly about training through evolution. In my approach sharing can be done implicitly (score of a particular kernel genome is the average of scores of all main networks using it). So you can think of kernels as "service providers". The most useful providers will survive.

The rationale is that we could reuse existing ConvNet architectures.

**About you proposal**, are you sure that the network could figure out how to create complex convolutional structures this way? 

Anyway, thanks for pointing!
