### ISSUE TITLE
reverse outputs order in training

### ISSUE THREAD

**Issue by makryl** [wagenaartje/neataptic#14]
Hello. Thanks for great project!

Looks like there is bug in way you getting target values when propagating errors
```js
propagate: function(rate, target){
    this.nodes.reverse();

    // Propagate nodes from end to start
    for(node in this.nodes){
      switch(this.nodes[node].type){
        case('hidden'):
          this.nodes[node].propagate(rate);
          break;
        case('output'):
          this.nodes[node].propagate(rate, target[node]);
          break;
      }
    }

    this.nodes.reverse();
  },
```
All nodes reversed, including outputs, but target values not.
By the way outputs can be in the middle of `nodes` array, not last, in this case `target[node]` can be undefined.
To save outputs order i suggest:
```js
propagate: function(rate, target){
    this.nodes.reverse();
    var targetIndex = target.length;
    // Propagate nodes from end to start
    for(node in this.nodes){
      switch(this.nodes[node].type){
        case('hidden'):
          this.nodes[node].propagate(rate);
          break;
        case('output'):
          this.nodes[node].propagate(rate, target[--targetIndex]);
          break;
      }
    }

    this.nodes.reverse();
  },
```

**Comment by wagenaartje** [comment]
Wow! This is a pretty heavy (and weird) bug. For some strange reason I havent noticed this yet, tomorrow ill do some debugging and try your implementation.

But why can output nodes be in the middle of this.nodes? I think I implemented it so that output nodes should be in the back of the array, as the list is also an activation order.

Thanks very much, ill start working on it asap 👍🏻

**Comment by wagenaartje** [comment]
I fixed this issue in this commit https://github.com/wagenaartje/neataptic/commit/9d6a9c8d54d34a087a9609a3c0d29aa1250074b4. But i'm still very curious why you said output nodes could be in the middle of the `this.nodes` array, so i'm leaving this issue open for now!

**Comment by makryl** [comment]
`neataptic.Architect.Construct` receives list of nodes or groups, but there is no restrictions on ordering and nodes goes into `network.nodes` in exact same order as in argument `list`

**Comment by wagenaartje** [comment]
Ahah. You're right. This is a bug in `Architect.Construct` then. I'll fix this soon, thanks for noticing this :thumbsup:

**Comment by wagenaartje** [comment]
Basically fixed in https://github.com/wagenaartje/neataptic/commit/a64a36f21a64884e883cdccc517cb44f0dbfe8fe. Please do keep in mind that you must always input your nodes/groups for `Architect.Construct()` in activation order. I added the following notice to the [Architect wiki](https://github.com/wagenaartje/neataptic/wiki/Architect):

> Keep in mind that you must always specify your input groups/nodes in activation order. Input and output nodes will automatically get sorted out, but all hidden nodes will be activated in the order that they were given.

**Comment by makryl** [comment]
thanx! :+1:

**Comment by wagenaartje** [comment]
I just wanted to inform you I implemented your use of `--targetIndex` in some way or another in the latest update :) https://github.com/wagenaartje/neataptic/commit/398e92b989ab62b81d2efd545c70fab7eedd50ba
