### ISSUE TITLE
new Neat() - cannot take the new mutation ADD_GATE?

### ISSUE THREAD

**Issue by tbarross** [wagenaartje/neataptic#3]
wanted to give a test run with the new mutations, not sure if this is only allowed on the LSTM architecture but when i run with the Neat class i seem to always get stuck in this line:
this.connections.gated.push(connection);
saying that the gated is undefined.

do i need to create a LSTM network for this mutation to work?

Regards,
Tim

**Comment by wagenaartje** [comment]
The `Neat` class does not accept the six new mutation methods yet. That's because I have not yet implemented crossover yet for networks with gates, selfconnections, etc. At this moment i'm working on it. There is a warning on the [mutation wiki page](https://github.com/wagenaartje/neataptic/wiki/Mutation): 

![img](https://i.gyazo.com/505089a671fa597e1f4dff97bf722067.png)

I'll resolve this issue when i've updated the crossover code!

**Comment by wagenaartje** [comment]
This has been added in the latest update (https://github.com/wagenaartje/neataptic/commit/6f08f82fc1bb343473b353691a75861fa113a710)!
