### ISSUE TITLE
Outputs are out of the [0, 1] range

### ISSUE THREAD

**Issue by AlexisTM** [wagenaartje/neataptic#44]
Hey again, 

I was testing the [neuroevolution playground](https://wagenaartje.github.io/neataptic/articles/neuroevolution/) and I got some outputs out of bounds (out of [0, 1]). 

Output of the neuroevolution example 2:
```
Input: [0], wanted output: [0], actual: [-0.026]
Input: [0], wanted output: [0], actual: [-0.02]
Input: [0], wanted output: [0], actual: [-0.013]
Input: [0], wanted output: [0], actual: [-0.006]
Input: [0], wanted output: [0], actual: [-0.001]
Input: [0], wanted output: [0], actual: [0.002]
Input: [0], wanted output: [0], actual: [0.004]
Input: [0], wanted output: [0], actual: [0.004]
Input: [0], wanted output: [0], actual: [0.014]
Input: [0], wanted output: [1], actual: [0.979]
```

**Comment by wagenaartje** [comment]
That is because [activation functions supported by Neataptic](https://wagenaartje.github.io/neataptic/docs/methods/activation/) are not all constrained to the [0, 1] range.

Sometimes having a neuron activation function that is not constrained to [0, 1] might benefit the convergence.

Ofcourse, it is possible to disable all activation functions during mutation that are not constrained. See [this](https://wagenaartje.github.io/neataptic/docs/methods/mutation/) page for more info.

**Comment by AlexisTM** [comment]
Well, I am for sure not an expert at all. 

Even if the activation function is not bounded by itself, shouldn't the neuron output itself be bounded before sending the output to another neuron?  

I feel like one unbounded neuron can "break" the network. An exponential neuron with 5 as input will break the ceiling and do the same to all subsequent neurons. 

I will do as you say, restraining the activation functions.

**Comment by wagenaartje** [comment]
> shouldn't the neuron output itself be bounded before sending the output to another neuron?

No, because a neurons output gets multiplied by an unbounded weight anyways before reaching another neuron. It is the receiving neuron's task to bound the values it receives.

**Most importantly**: Mind that neurons can have infinite incoming connections, so if you have a neuron with 100 inputting connections coming from bounded neurons (to `[0, 1]`), that still would mean that the input to that neuron could be 100, disregarding the weights. 

And an unbounded neuron won't break the network. If you input the value of an unbounded neuron to a bounded neuron, the value will become bounded again.

It is actually quite common for certain neural network to use unbounded neuron activations. For example, [Rectified Linear Units](https://en.wikipedia.org/wiki/Rectifier_(neural_networks)).

<hr>

I looked up something online, and I think this might be a nice read: http://www.sciencedirect.com/science/article/pii/S1063520315001748

> it is shown that a neural network with unbounded activation functions still satisfies the universal approximation property

Feel free to ask any more questions :+1:

**Comment by AlexisTM** [comment]
Thanks for the explanation! I think I can close it as it is not a bug at all.
